### ISSUE TITLE
image_test

### ISSUE THREAD

**Issue by GentlesJan** [SiyuanHuang95/ManipVQA#1]
Hi!

How can I quickly test the performance of your pre-trained model on new images?

Thanks!

**Comment by SiyuanHuang95** [comment]
Hi, thanks for your interest in our project.

To run our model, you need 2-A100 GPUs if you want to run locally. 

If you just wanna give a quick trial (limited images), you can send the images and the corresponding question prompts in a text file, and I would try to run it on the lab's cluster. You can send me via email: anthonyhuang4de@gmail.com

**Comment by SiyuanHuang95** [comment]
Since no following message, I will close this issue. You can reopen it whenever you need it. @GentlesJan
