### ISSUE TITLE
LLM dir seems incomplete

### ISSUE THREAD

**Issue by zaixing-wang** [SiyuanHuang95/ManipVQA#5]
I tried to run eval, but suffered some issues:
 ModuleNotFoundError: No module named 'accessory.model.LLM.pointbert'
 ModuleNotFoundError: No module named 'accessory.model.LLM.llama_qformerv2'

**Comment by SiyuanHuang95** [comment]
thanks for your interests in our project, and pointing out the small typos in the codes.

These two lines are irrelevant and have been removed now. 

For any further question, please let me know

**Comment by zaixing-wang** [comment]
> thanks for your interests in our project, and pointing out the small typos in the codes.
> 
> These two lines are irrelevant and have been removed now.
> 
> For any further question, please let me know

Thank you for your helpful response.
